# Bluetooth & Controller
CONFIG_BT=y
CONFIG_BT_CTLR=y

# DTM 애플리케이션 활성화 (위에서 추가한 Kconfig 심볼 사용)
CONFIG_BT_DTM_APP=y

# DTM sample dependencies
CONFIG_NRFX_TIMER0=y
CONFIG_NRFX_TIMER1=y
CONFIG_NRFX_TIMER2=y
CONFIG_NRFX_GPPI=y
CONFIG_CLOCK_CONTROL=y

# NFC 핀(P0.09) GPIO로 해제 (v3.1.0 권장 심볼)
CONFIG_NFCT_PINS_AS_GPIOS=y

# 안테나 게인 보정 (0dBm)
CONFIG_BT_CTLR_TX_PWR_ANTENNA=0

# UART 설정
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
# HWFC는 Overlay 파일에서 제거

# 로그 및 콘솔 비활성화 (DTM 바이너리 통신 간섭 방지)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_BOOT_BANNER=n
CONFIG_EARLY_CONSOLE=n
CONFIG_PRINTK=n

# 시스템 클럭 (HFXO 사용)
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_20PPM=y
